name: 'swift-package'
description: "Set of utils for CI of multiplatform swift packages"
author: 'capturecontext'
inputs:
  xcode:
    description: Xcode version
    required: false
    default: '26.2'
  cache-derived-data:
    description: "Specifies if DerivedData should be cached"
    required: false
    default: false
  cache-derived-data-base-path:
    description: "Base path for DerivedData caching"
    required: false
    default: ~/.derivedData
  cache-derived-data-prefix:
    description: "Prefix for caching key"
    required: false
    default: __unspecified__
  cache-derived-data-suffix:
    description: "Suffix for caching key, likely to be files hash"
    required: false
    default: __unspecified__
  command:
    description: "MAKE command to run"
    required: false
  subcommand:
    description: "COMMAND argument for make action"
    required: false
    default: __unspecified__
  workspace:
    description: "Path to xcworkspace for xcodebuild actions"
    required: false
    default: .swiftpm/xcode/package.xcworkspace
  scheme:
    description: "Scheme"
    required: false
    default: __unspecified__
  platform:
    description: "Platform"
    required: false
    default: __unspecified__
  config:
    description: "Config"
    required: false
    default: Debug
  beautify:
    description: "Beautify"
    required: false
    default: quiet
  working-directory:
    description: "Where to run the action"
    required: false
    default: '.'
  swift-format-commit-message:
    description: "Commit message for format action"
    required: false
    default: '[swift-format]'
  swift-format-branch:
    description: "Branch for committing result of format action"
    required: false
    default: 'main'
branding:
  icon: 'package'
  color: 'gray-dark'
runs:
  using: "composite"
  steps:
    - name: Setup venv
      uses: capturecontext/swift-package-action/setup-venv@main
    - name: Select Xcode ${{ inputs.xcode }}
      uses: capturecontext/swift-package-action/xcode-select@main
      with:
        version: ${{ inputs.xcode }}
    - name: Install visionOS runtime
      if: inputs.platform == visionOS
      uses: capturecontext/swift-package-action/install-visionos@main
    - name: List available devices
      if: inputs.platform != '__unspecified__'
      shell: bash
      run: xcrun simctl list devices available
    - name: Cache derived data
      if: | 
        inputs.cache-derived-data == true ||
        inputs.command == cache-derived-data
      uses: capturecontext/swift-package-action/cache/derived-data@main
      with:
        path: ${{ inputs.cache-derived-data-base-path }}
        prefix: ${{ inputs.cache-derived-data-prefix }}
        platform: ${{ inputs.platform }}
        xcode: ${{ inputs.xcode }}
        command: ${{ inputs.subcommand }}
        suffix: ${{ inputs.suffix }}
    - name: Set IgnoreFileSystemDeviceInodeChanges flag
      shell: bash
      run: defaults write com.apple.dt.XCBuild IgnoreFileSystemDeviceInodeChanges -bool YES
    - name: Update mtime for incremental builds
      uses: chetan/git-restore-mtime-action@v2
    - name: Run ${{ inputs.command }}
      if: |
        inputs.command != '__unspecified__' &&
        inputs.command != 'cache-derived-data'
      shell: bash
      run: |
        # run-${{ inputs.command }} step

        echo "$GITHUB_ACTION_PATH"

        cd "${{ inputs.working-directory }}"
        make ${{ inputs.command }} \
          -f "$GITHUB_ACTION_PATH"/Makefile \
          ACTION_PATH="$GITHUB_ACTION_PATH" \
          WORKSPACE="${{ inputs.workspace }}" \
          SCHEME="${{ inputs.scheme }}" \
          PLATFORM="${{ inputs.platform }}" \
          CONFIG="${{ inputs.config }}" \
          BEAUTIFY="${{ inputs.beautify }}"
    - name: Commit swift-format
      if: inputs.command == swift-format
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: ${{ inputs.swift-format-commit-message }}
        branch: ${{ inputs.swift-format-branch }}
