name: 'swift-package-setup-venv'
description: 'Create python virtual environment for running actions'
author: 'capturecontext'

branding:
  icon: 'archive'
  color: 'gray-dark'

inputs:
  working-directory:
    description: "Where to run the action"
    required: false
    default: '.'

runs:
  using: 'composite'
  steps:
    - id: print-action-path
      name: Print GITHUB_ACTION_PATH
      uses: capturecontext/swift-package-action/print-action-path@main
      with:
        name: "swift-package-setup-venv"
        path: ${{ github.action_path }}

    - id: install-python
      name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - id: create-venv
      name: Create .venv
      shell: bash
      run: |
        # create-venv step

        cd "${{ inputs.working-directory }}"
        make venv \
          -f "$GITHUB_ACTION_PATH"/Makefile
