name: 'swift-package-print-action-path'
description: "Prints action path for visual feedback in composite actions"
author: 'capturecontext'

branding:
  icon: 'package'
  color: 'gray-dark'

inputs:
  name: 
    description: "Name of the action"
    required: false
    default: "print-action-path step"
  path:
    description: "github.action_path to print"
    required: true

runs:
  using: "composite"
  steps:
    - id: print-action-path
      name: Print input path
      shell: bash
      run: |
        # ${{ inputs.name }}
        echo "${{ inputs.path }}"
