name: 'swift-package-print-action'
description: "Prints action path for visual feedback in composite actions"
author: 'capturecontext'

branding:
  icon: 'package'
  color: 'gray-dark'

inputs:
  name: 
    description: "Name of the action"
    required: false
    default: "print-action step"
  path:
    description: "github.action_path to print"
    required: false
    default: __unspecified__

runs:
  using: "composite"
  steps:
    - id: print-action
      name: Print action
      shell: bash
      run: |
        # ${{ inputs.name }}
        [[ "${{ inputs.path }}" != "__unspecified__" ]] && echo "${{ inputs.path }}"
