name: 'swift-package-xcode-select'
description: 'Select xcode version'
author: 'capturecontext'

branding:
  icon: 'archive'
  color: 'gray-dark'

inputs:
  version:
    description: Xcode version
    required: false
    default: '26.2'

runs:
  using: 'composite'
  steps:
    - id: print-action-path
      name: Print GITHUB_ACTION_PATH
      uses: capturecontext/swift-package-action/print-action@3.0-beta.14
      with:
        name: "swift-package-xcode-select"

    - id: select-xcode
      name: Select Xcode ${{ inputs.version }}
      if: inputs.version != '__unspecified__'
      shell: bash
      run: |
        # select-xcode step

        make select-xcode \
          -f "$GITHUB_ACTION_PATH"/Makefile \
          VERSION=${{ inputs.version }} 
