name: 'swift-package-install-visionos'
description: 'Install visionOS runtime'
author: 'capturecontext'

branding:
  icon: 'archive'
  color: 'gray-dark'

runs:
  using: 'composite'
  steps:
    - id: print-action-path
      name: Print GITHUB_ACTION_PATH
      uses: capturecontext/swift-package-action/print-action-path@main
      with:
        name: "swift-package-install-visionos"
        path: ${{ github.action_path }}

    - id: install-visionos
      name: Install visionOS runtime
      shell: bash
      run: |
        # install-visionos step

        sudo xcodebuild -runFirstLaunch
        sudo xcrun simctl list
        sudo xcodebuild -downloadPlatform visionOS
        sudo xcodebuild -runFirstLaunch
